services:
  #OPC-UA server
  opc:
    build:
      context: .
      target: OPC-Server
    container_name: opc-server
    ports:
      - "4334:4334"
    networks:
      - advanced_data_management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  #OPC-UA server message converter to mqtt
  mqtt-agent:
    build:
      context: .
      target: MQTT-Agent
    container_name: mqtt-agent
    networks:
      - advanced_data_management
    environment:
      OPCUA: "opc.tcp://opc:4334/UA/fhvopcserver"
      MQTT: "mqtt://mqtt:1883"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mqtt
      - opc

  #MQTT broker
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - './mosquitto-data:/etc/mosquitto'
      - './mosquitto-data/mosquitto.conf:/mosquitto/config/mosquitto.conf'
    networks:
      - advanced_data_management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  #Redis
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis-data:/data
    networks:
      - advanced_data_management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  #Redpanda (Kafka)
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    volumes:
      - ./redpanda-data:/var/lib/redpanda/data
    networks:
      - advanced_data_management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1" ]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  #Redpanda console to see messages
  redpanda_console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda_console
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - "8085:8080"
    networks:
      - advanced_data_management
    depends_on:
      redpanda:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis hydration agent which enriches incoming mqtt events with information from redis
  redis_hydration:
    image: docker.redpanda.com/redpandadata/connect:latest
    container_name: redis_hydration
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mqtt
      - redis
    networks:
      - advanced_data_management
    volumes:
      - ./redis_hydration.yaml:/connect.yaml

  # Agent which writes information from mqtt broker to Redpanda
  mqtt_kafka_bridge:
    image: docker.redpanda.com/redpandadata/connect:latest
    container_name: mqtt_kafka_bridge
    restart: unless-stopped
    volumes:
      - ./mqtt_to_kafka.yaml:/connect.yaml
    networks:
      - advanced_data_management
    depends_on:
      mqtt:
        condition: service_started
      redpanda:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:4195/ready" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # postgresql
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/pgdata
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./timescaledb/data:/pgdata
      - ./timescaledb/init:/docker-entrypoint-initdb.d
    networks:
      - advanced_data_management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Agent which publishes messages from Redpanda to postgresql (timescaledb)
  kafka_to_timescaledb:
    image: docker.redpanda.com/redpandadata/connect:latest
    container_name: kafka_to_timescaledb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mqtt_kafka_bridge
      - redpanda
      - timescaledb
    networks:
      - advanced_data_management
    volumes:
      - ./kafka_to_timescale.yaml:/connect.yaml
      - ./connect-state:/var/lib/redpanda-connect

  #grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - advanced_data_management
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"



networks:
  advanced_data_management:
    external: true
